### ISSUE TITLE
Create, Update, Delete commands for Events

### ISSUE THREAD

**Issue by clydelhui** [AY2223S2-CS2103T-T09-2/tp#12]
As a student, I can create, update and delete my events so that I can keep my event list up to date.

**Comment by Alvozyn** [comment]
- [ ] Create recurring event

**Comment by gmengqi** [comment]
Non-recurring event 

- [ ] Create event 
- [ ] Update event
- [ ] Delete event 
- [ ] To string

**Comment by clydelhui** [comment]
- [ ] Event Abstract Class
- [ ] EventList
- [ ] List Command
