### ISSUE TITLE
[PE-D][Tester D] Error in description of edit in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T09-2/tp#125]
>edit 3 m/ t/Borrowed $10 Edit the tags of the 2nd person to be Borrowed $10 plus the existing tag of that person.
> edit 3 m/ g/CS2103T Edit the groups of the 2nd person to be CS2103T plus the existing groups of that person.

From the UG, the tags and groups of the 3rd person is edited instead.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: joellow88/ped#1

**Comment by lyndonlim27** [comment]
Completed. [PR #162](https://github.com/AY2223S2-CS2103T-T09-2/tp/pull/162)
