### ISSUE TITLE
[PE-D][Tester D] Unexpected behaviour in group_create

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T09-2/tp#126]
When doing command `group_create g/CS1231 g/CS1233`, only one group (CS1233) is created. Prefer to show invalid input or to create multiple groups.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: joellow88/ped#2

**Comment by lyndonlim27** [comment]
Completed. [PR #162](https://github.com/AY2223S2-CS2103T-T09-2/tp/pull/162)
