### ISSUE TITLE
[PE-D][Tester D] User guide not clear about event time requirements

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T09-2/tp#133]
Events can only be added in 1h timeslots. User guide did not specify this requirement.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: joellow88/ped#5

**Comment by lyndonlim27** [comment]
Completed. [PR #165](https://github.com/AY2223S2-CS2103T-T09-2/tp/pull/165
