### ISSUE TITLE
[PE-D][Tester A] UG does not mention that group names must be alphanumeric

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T09-2/tp#135]
![image.png](https://raw.githubusercontent.com/9fc70c892/ped/main/files/750b0933-d29f-4f4e-951b-fafae67e3d55.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: 9fc70c892/ped#2

**Comment by lyndonlim27** [comment]
Updated UG. Completed. [PR #166](https://github.com/AY2223S2-CS2103T-T09-2/tp/pull/166)
