### ISSUE TITLE
[PE-D][Tester A] DG does not mention that index is from the printed list

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-T09-2/tp#141]
How to recreate:
- Find names that doesn't exist
- run command

![image.png](https://raw.githubusercontent.com/9fc70c892/ped/main/files/0be00dac-4bb2-4751-bf5e-9404f8ae6c59.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: 9fc70c892/ped#5

**Comment by lyndonlim27** [comment]
Completed. [PR #162](https://github.com/AY2223S2-CS2103T-T09-2/tp/pull/162)
