### ISSUE TITLE
[PE-D][Tester E] Unable to add tags of the same name even with the merge command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T09-2/tp#146]
As stated in the title, even with the merge command, I am unable to add tags of the same name, nor is there any error thrown. Maybe this should be reflected in the user guide, or in and error message if this is indeed the expected behaviour. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: seriouslia0/ped#10

**Comment by lyndonlim27** [comment]
Unable to add new exception due to feature freeze. But included in UG. Completed. [PR #170](https://github.com/AY2223S2-CS2103T-T09-2/tp/pull/170)
