### ISSUE TITLE
Update Developer Guide

### ISSUE THREAD

**Issue by clydelhui** [AY2223S2-CS2103T-T09-2/tp#5]
As a developer, I can read the developer guide so that I know how I can modify and contribute to the project.

**Comment by Alvozyn** [comment]
- [ ] User Profile @Alvozyn 
- [ ] Value proposition @edures888 
- [ ] User stories @gmengqi 
- [ ] Use cases @clydelhui 
- [ ] Non-functional requirements @lyndonlim27
